"""Removed some more  column from email_metadata model

Revision ID: 62dc66bbd144
Revises: 427efd7a4285
Create Date: 2026-01-11 17:31:11.077449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62dc66bbd144'
down_revision: Union[str, Sequence[str], None] = '427efd7a4285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('EmailData', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EmailData', sa.Column('status', postgresql.ENUM('pending', 'uploaded', 'processing', 'completed', 'failed', 'incomplete', name='statusenum'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
