"""Added changes in AttachementData table

Revision ID: 7bfa23fd18ca
Revises: bd9bf513fb76
Create Date: 2026-01-08 21:19:52.678801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bfa23fd18ca'
down_revision: Union[str, Sequence[str], None] = 'bd9bf513fb76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AttachmentData', sa.Column('file_name', sa.String(), nullable=True))
    op.add_column('AttachmentData', sa.Column('file_size', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AttachmentData', 'file_size')
    op.drop_column('AttachmentData', 'file_name')
    # ### end Alembic commands ###
