"""Added modification

Revision ID: a465293df64c
Revises: 6a6b8a6ce2b4
Create Date: 2025-12-29 23:24:28.508681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a465293df64c'
down_revision: Union[str, Sequence[str], None] = '6a6b8a6ce2b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EmailData',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imap_uid', sa.String(), nullable=False),
    sa.Column('total_pdfs', sa.Integer(), nullable=True),
    sa.Column('processed_pdfs', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imap_uid')
    )
    op.create_table('AttachmentData',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=True),
    sa.Column('cloudinary_reportUrl', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'uploaded', 'processing', 'completed', 'failed', name='statusenum'), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['EmailData.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Report Data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Report Data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reportUrl', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('processed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('stored', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('Report Data_pkey'))
    )
    op.drop_table('AttachmentData')
    op.drop_table('EmailData')
    # ### end Alembic commands ###
