"""Added some column from email_metadata model

Revision ID: 2cfe8dbf5924
Revises: 62dc66bbd144
Create Date: 2026-01-11 17:56:01.422129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cfe8dbf5924'
down_revision: Union[str, Sequence[str], None] = '62dc66bbd144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EmailData', sa.Column('status', sa.Enum('pending', 'uploaded', 'processing', 'completed', 'incomplete', 'failed', name='statusenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('EmailData', 'status')
    # ### end Alembic commands ###
