"""Added modification

Revision ID: 3630ed698139
Revises: a465293df64c
Create Date: 2025-12-31 22:55:37.506159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3630ed698139'
down_revision: Union[str, Sequence[str], None] = 'a465293df64c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EmailData', sa.Column('status', sa.Enum('pending', 'uploaded', 'processing', 'completed', 'incomplete', 'failed', name='statusenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('EmailData', 'status')
    # ### end Alembic commands ###
