"""Removed some column from email_metadata model

Revision ID: 427efd7a4285
Revises: 9e234b8c64a6
Create Date: 2026-01-11 17:28:04.607217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '427efd7a4285'
down_revision: Union[str, Sequence[str], None] = '9e234b8c64a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('EmailData', 'total_pdfs')
    op.drop_column('EmailData', 'processed_pdfs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EmailData', sa.Column('processed_pdfs', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('EmailData', sa.Column('total_pdfs', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
