"""Added stored column in table

Revision ID: 6a6b8a6ce2b4
Revises: b200eafe2ba9
Create Date: 2025-12-28 22:32:30.863790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a6b8a6ce2b4'
down_revision: Union[str, Sequence[str], None] = 'b200eafe2ba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Report Data', sa.Column('stored', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Report Data', 'stored')
    # ### end Alembic commands ###
