"""Added column in AttachementData table for storing checksum of file

Revision ID: 9e234b8c64a6
Revises: 7bfa23fd18ca
Create Date: 2026-01-08 23:04:42.680605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e234b8c64a6'
down_revision: Union[str, Sequence[str], None] = '7bfa23fd18ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AttachmentData', sa.Column('checksum_sha256', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AttachmentData', 'checksum_sha256')
    # ### end Alembic commands ###
