"""Added some more columns in EmailData table

Revision ID: b1898a40748e
Revises: 181a65abf74a
Create Date: 2026-01-02 13:14:07.427242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1898a40748e'
down_revision: Union[str, Sequence[str], None] = '181a65abf74a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EmailData', sa.Column('mail_from', sa.String(), nullable=False))
    op.add_column('EmailData', sa.Column('subject', sa.String(), nullable=True))
    op.add_column('EmailData', sa.Column('received_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('EmailData', 'received_at')
    op.drop_column('EmailData', 'subject')
    op.drop_column('EmailData', 'mail_from')
    # ### end Alembic commands ###
