"""Added new columns on report table

Revision ID: 210f36707a04
Revises: 
Create Date: 2026-04-06 12:35:58.561297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '210f36707a04'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.add_column('generated_reports', sa.Column('tiptap_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('generated_reports', sa.Column('source_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('generated_reports', sa.Column('html_cache', sa.Text(), nullable=True))
    op.add_column('generated_reports', sa.Column('s3_key', sa.String(), nullable=True))
    op.add_column('generated_reports', sa.Column('export_format', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_reports', 'export_format')
    op.drop_column('generated_reports', 's3_key')
    op.drop_column('generated_reports', 'html_cache')
    op.drop_column('generated_reports', 'source_map')
    op.drop_column('generated_reports', 'tiptap_json')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
