"""Added property in mail data

Revision ID: 5969be2587c6
Revises: 9aa5228d2eb6
Create Date: 2026-03-13 02:05:38.786318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5969be2587c6'
down_revision: Union[str, Sequence[str], None] = '9aa5228d2eb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.add_column('AttachmentData', sa.Column('imap_uid', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('AttachmentData_email_id_fkey'), 'AttachmentData', type_='foreignkey')
    op.create_foreign_key(None, 'AttachmentData', 'EmailData', ['imap_uid'], ['imap_uid'])
    op.drop_column('AttachmentData', 'email_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AttachmentData', sa.Column('email_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'AttachmentData', type_='foreignkey')
    op.create_foreign_key(op.f('AttachmentData_email_id_fkey'), 'AttachmentData', 'EmailData', ['email_id'], ['imap_uid'])
    op.drop_column('AttachmentData', 'imap_uid')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
